apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
    domain: saas.finline.app
    externalDNS: false
    namespaceSubDomain: .
    tls:
      email: lizheng2@sunline.cn
      enabled: true
      production: false
      secretName: jx-privkey
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
