apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    environmentGitOwner: q1323829945
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    domain: saas.finline.app
    kind: ingress
    namespaceSubDomain: .
    tls:
      email: lizheng2@sunline.cn
      enabled: true
      production: false
      secretName: jx-privkey
  pipelineUser:
    username: q1323829945
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
