filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: https://chartmuseum-jx.saas-ops.finline.app
releases:
- chart: dev/test2
  version: 0.0.2
  name: test2
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
